bot:
  name: "chat bot"
  token: "YOUR_DISCORD_KEY" # Bot token from Discord Developer Portal https://discord.com/developers/applications/
  prefix: "chatbot" #the preffix of the bot
  use_short_prefix: true #Set True if you want to use a short preffix
  short_prefix: "cb" #A short freffix for the bot
  time_out: 100 #A time_out in ms, that represent the timeout in the QueueThread
  use_copypasta: true #If you don't want this command set False
  use_ask_tts: true  #If you don't want this command set False
  use_audio: true #This will allow all the audio related commands, this requiere mmpeg (This is not suported by Replit)
  use_google_cloud_service: True #If true us Google Cloud Text to Speech for this you must setup gCloud on your device and using google cloud isn't free, if False it will use google gTTS a free service that allow Text-To-Speech

open_ai:
  token: "YOUR_OPEN_AI_KEY" # OpenAI key from OpenAI Developer Account https://platform.openai.com/account/api-keys
  model: "gpt-3.5-turbo"  # The model that you want to use
  temperature: "2"
  role: "You are a helpful assistant." # The role of the bot, this change the behavior of the chat bot

text: #Customize the answers to some commands of the bot
  help: "This is under build"
  hello: "Hello, i'm ChatBot a Python Discord Bot"
  version: "Hi there, my current release is: 0.9.0 BETA"
  reset_error: "My prompt is empty so i can't reboot"
  reset_success: "I have rebooted successfully"
  role_changed: "I changed my role to "
  join_error: "I can't join because you are not currently in a voice chat"
  join_success: "Successfully joined the voice chat"
  leave_error: "I'm not in a voice channel so i can't leave it"
  leave_success: "I leave the voice channel successfully"
  copypasta: [
    "copypasta_test_1",
    "copypasta_test_2",
    "copypasta_test_3"
  ]

command: #customize the command to execute certain functions, the commands can be found in 
  help: "help"
  hello: "hello" #Respond to your greeting
  copypasta: "copypasta" #Display one of the copypastas in list
  version: "version" #Display current release
  ask: "ask" #Ask something to the chat bot
  ask_tts: "tts" #Ask something to the chat bot and the answers will be a tts message
  reset: "reset" #Reset the chat history (This can speed up answers and reduce tokens consumption but the bot will lose the context)
  change_role: "changerole" #change the role of the bot, this change bot's behavior
  join: "join" #Join to the voice channel where the user that calls the command is currently
  leave: "leave" #Leave the voice channel
  ask_voice: "voice" #Ask something to the chat bot and the answers will be a voice answer in the current channel

status:
  use_status: true # If you want to set a custom status for your bot
  status_type:  "game" # game: 'Playing' status | streaming: 'Streaming' status | listening: 'Listening' status | watching: 'Watching' status
  streaming_url: "" #Only use if status_type is streaming
  use_help_command: True #Only use if you are going to use {help_command} this will show the prefix.help command in the text
  text: "Genshin Impact | {help_command} for help" # the text that will display in the status, if use_help_command: True, remeber to add {help_command} where you want to display the help command


TTS:
  engine: "gcloud" #if glocud the bot will use gcloud for the TTS you must setup gcloud on your device using gcloud, if gtts the bot will use gtts for the TTS
  model: "en-US-Standard-C" #change this only if you are using gcloud, check all the models in https://cloud.google.com/text-to-speech/docs/voices
  language: "en" #change this only if using gtts, check all the language in https://gtts.readthedocs.io/en/latest/module.html#localized-accents
  tld: "us" #change this only if using gtts, check the TLD in https://gtts.readthedocs.io/en/latest/module.html#localized-accents
  