bot:
  name: "chat bot"
  token: "YOUR_DISCORD_KEY" # Bot token from Discord Developer Portal https://discord.com/developers/applications/
  prefix: "chatbot" #the preffix of the bot
  use_short_prefix: true #Set True if you want to use a short preffix
  short_prefix: "cb" #A short freffix for the bot
  use_copypasta: true #If you don't want this command set False
  use_ask_tts: true  #If you don't want this command set False

open_ai:
  token: "YOUR_OPEN_AI_KEY" # OpenAI key from OpenAI Developer Account https://platform.openai.com/account/api-keys
  model: "gpt-3.5-turbo"  # The model that you want to use
  role: "You are a helpful assistant." # The role of the bot, this change the behavior of the chat bot

text: #Customize the answers to some commands of the bot
  help: "This is under build"
  hello: "Hello, i'm ChatBot a Python Discord Bot"
  version: "Hi there, my current release is: 0.9.0 BETA"
  reset_error: "My prompt is empty so i can't reboot"
  reset_success: "I have rebooted successfully"
  role_changed: "I changed my role to "
  copypasta: [
    "copypasta_test_1",
    "copypasta_test_2",
    "copypasta_test_3"
  ]

command: #customize the command to execute certain functions, the commands can be found in 
  help: "help"
  hello: "hello" #Respond to your greeting
  copypasta: "copypasta" #Display one of the copypastas in list
  version: "version" #Display current release
  ask: "ask" #ask something to the chat bot
  ask_tts: "tts" #ask something to the chat bot and the answers will be a tts message
  reset: "reset" #reset the chat history (This can speed up answers and reduce tokens consumption but the bot will lose the context)
  change_role: "changerole" #change the role of the bot, this change bot's behavior 